# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - webApp-r2eh2kyuiqgke

on:
  push:
    branches:
      - main

    paths:
    # Any change to code, infra as code and configuration
    - "deploy/**"
    - "services/**"
     # Changes to the workflow
    - ".github/workflows/main_webapp-r2eh2kyuiqgke.yml"
  workflow_dispatch:


env:
  PROJECT_PATH: './services/webapi/src/webapi.csproj'
  TEST_PATH: './services/webapi/tests/'
  OUTPUT_PATH: './output/webapi/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.404

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }}

      - name: Test
        run: dotnet test ${{ env.TEST_PATH }}

      - name: Publish
        run: dotnet publish --no-build --output ${{ env.OUTPUT_PATH }} ${{ env.PROJECT_PATH }}

      - name: Package webapi
        run: (cd ${{ env.OUTPUT_PATH }} && zip -r ../../webapi.zip .)

      - name: Upload application zip package
        uses: actions/upload-artifact@v2
        with:
          name: webapi
          path: ./webapi.zip
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webApp-r2eh2kyuiqgke'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CFEA7C22C60349CC980DA022D1BD3D4F }}
          package: .
